In [5]:
import  pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import silhouette_score
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

# Import dataset into jupyter notebook

In [6]:
df= pd.read_csv("Mall_Customers.csv") 
df.head()

   CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0           1    Male   19                  15                      39
1           2    Male   21                  15                      81
2           3  Female   20                  16                       6
3           4  Female   23                  16                      77
4           5  Female   31                  17                      40

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 5 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   CustomerID              200 non-null    int64
 1   Gender                  200 non-null    str
 2   Age                     200 non-null    int64
 3   Annual Income (k$)      200 non-null    int64
 4   Spending Score (1-100)  200 non-null    int64
dtypes: int64(4), str(1)
memory usage: 7.9 KB

In [8]:
df.describe()

       CustomerID         Age  Annual Income (k$)  Spending Score (1-100)
count  200.000000  200.000000          200.000000              200.000000
mean   100.500000   38.850000           60.560000               50.200000
std     57.879185   13.969007           26.264721               25.823522
min      1.000000   18.000000           15.000000                1.000000
25%     50.750000   28.750000           41.500000               34.750000
50%    100.500000   36.000000           61.500000               50.000000
75%    150.250000   49.000000           78.000000               73.000000
max    200.000000   70.000000          137.000000               99.000000

# Check for missing numbers

In [9]:
df.isnull().sum()

CustomerID                0
Gender                    0
Age                       0
Annual Income (k$)        0
Spending Score (1-100)    0
dtype: int64

Encode dataset

In [10]:
df["Gender"].unique()

<StringArray>
['Male', 'Female']
Length: 2, dtype: str

In [12]:
cat_col = df["Gender"]   
print (cat_col)

0        Male
1        Male
2      Female
3      Female
4      Female
        ...
195    Female
196    Female
197      Male
198      Male
199      Male
Name: Gender, Length: 200, dtype: str

# Encoding by mapping

In [13]:
df["Gender"]=df["Gender"].map({"Male":0,"Female":1})

In [90]:
df.head(200)

     CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0             1       0   19                  15                      39
1             2       0   21                  15                      81
2             3       1   20                  16                       6
3             4       1   23                  16                      77
4             5       1   31                  17                      40
..          ...     ...  ...                 ...                     ...
195         196       1   35                 120                      79
196         197       1   45                 126                      28
197         198       0   32                 126                      74
198         199       0   32                 137                      18
199         200       0   30                 137                      83

[200 rows x 5 columns]

In [14]:
X=df.head(200)
print (X)

     CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0             1       0   19                  15                      39
1             2       0   21                  15                      81
2             3       1   20                  16                       6
3             4       1   23                  16                      77
4             5       1   31                  17                      40
..          ...     ...  ...                 ...                     ...
195         196       1   35                 120                      79
196         197       1   45                 126                      28
197         198       0   32                 126                      74
198         199       0   32                 137                      18
199         200       0   30                 137                      83

[200 rows x 5 columns]

Divide features into training and testing set

In [15]:
X_train,X_test=train_test_split(X,train_size=0.8,random_state=9)

In [93]:
print (X_train)

     CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
146         147       0   48                  77                      36
169         170       0   32                  87                      63
145         146       0   28                  77                      97
55           56       0   47                  43                      41
21           22       0   25                  24                      73
..          ...     ...  ...                 ...                     ...
56           57       1   51                  44                      50
182         183       0   46                  98                      15
199         200       0   30                 137                      83
92           93       0   48                  60                      49
126         127       0   43                  71                      35

[160 rows x 5 columns]

In [16]:
print(X_test)

     CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
84           85       1   21                  54                      57
60           61       0   70                  46                      56
54           55       1   50                  43                      45
109         110       0   66                  63                      48
156         157       0   37                  78                       1
140         141       1   57                  75                       5
39           40       1   20                  37                      75
116         117       1   63                  65                      43
123         124       0   39                  69                      91
53           54       0   59                  43                      60
103         104       0   26                  62                      55
101         102       1   49                  62                      48
158         159       0   34                  78                       1
3             4       1   23                  16                      77
100         101       1   23                  62                      41
27           28       0   35                  28                      61
163         164       1   31                  81                      93
174         175       1   52                  88                      13
37           38       1   30                  34                      73
69           70       1   32                  48                      47
131         132       0   39                  71                      75
196         197       1   45                 126                      28
190         191       1   34                 103                      23
23           24       0   31                  25                      73
198         199       0   32                 137                      18
17           18       0   20                  21                      66
32           33       0   53                  33                       4
31           32       1   21                  30                      73
77           78       0   40                  54                      48
20           21       0   35                  24                      35
9            10       1   30                  19                      72
80           81       0   57                  54                      51
135         136       1   29                  73                      88
30           31       0   60                  30                       4
38           39       1   36                  37                      26
134         135       0   20                  73                       5
26           27       1   45                  28                      32
151         152       0   39                  78                      88
44           45       1   49                  39                      28
13           14       1   24                  20                      77

# import scaler

In [17]:
scaler =StandardScaler()  
scaler.fit_transform(X_train)

array([[ 0.75558836, -1.14840785,  0.6572178 ,  0.59038276, -0.58718017],
       [ 1.15833534, -1.14840785, -0.49044767,  0.98152662,  0.48042014],
       [ 0.73807762, -1.14840785, -0.77736403,  0.59038276,  1.8248057 ],
       [-0.83788883, -1.14840785,  0.58548871, -0.73950636, -0.38947641],
       [-1.43325393, -1.14840785, -0.99255131, -1.48267969,  0.87582765],
       [-1.31067876,  0.87077078,  0.08338507, -1.28710776, -0.78488393],
       [-0.62775997,  0.87077078,  2.09179964, -0.54393443, -0.11269114],
       [-0.48767406, -1.14840785, -0.92082222, -0.30924811,  0.12455337],
       [ 1.64863601, -1.14840785, -0.49044767,  2.50698767,  0.91536841],
       [-0.97797474,  0.87077078, -0.84909313, -0.85684952, -0.15223189],
       [ 1.50855011,  0.87077078, -0.2035313 ,  1.6073568 ,  1.35031668],
       [-1.36321098, -1.14840785, -0.70563494, -1.32622215,  1.23169442],
       [ 1.12331386,  0.87077078, -0.41871857,  0.94241224,  1.7457242 ],
       [ 1.10580313, -1.14840785,  0.22684325,  0.94241224, -1.2198322 ],
       [-0.1374593 , -1.14840785, -1.0642804 , -0.0745618 ,  0.04547186],
       [ 0.17773399, -1.14840785, -1.42292586,  0.08189575, -0.19177265],
       [ 1.56108232, -1.14840785, -0.41871857,  1.99850065, -1.69432122],
       [-1.53831836, -1.14840785, -1.20773859, -1.63913723,  1.11307217],
       [-0.90793178, -1.14840785, -0.41871857, -0.77862074,  0.36179788],
       [-1.69591501,  0.87077078, -0.27526039, -1.71736601, -1.77340272],
       [ 0.52794876,  0.87077078, -0.56217676,  0.39481083,  0.79674615],
       [ 0.58048098,  0.87077078,  0.37030144,  0.43392522, -1.73386197],
       [ 0.89567427,  0.87077078,  0.58548871,  0.62949715, -1.3779952 ],
       [ 1.29842125, -1.14840785, -0.84909313,  1.02064101,  0.71766465],
       [-0.61024923, -1.14840785, -1.42292586, -0.54393443,  0.32225713],
       [ 1.17584608, -1.14840785,  0.08338507,  0.98152662, -1.49661746],
       [ 0.05515883,  0.87077078,  1.94834146,  0.04278136, -0.03360964],
       [-0.17248077,  0.87077078,  0.08338507, -0.0745618 , -0.42901716],
       [-0.24252373,  0.87077078,  0.80067599, -0.15279057, -0.19177265],
       [-0.55771702,  0.87077078,  0.58548871, -0.50482004, -0.34993565],
       [ 0.3178199 ,  0.87077078, -0.06007311,  0.1992389 , -0.42901716],
       [-0.52269554,  0.87077078,  1.51796691, -0.46570566,  0.20363487],
       [-1.76595796,  0.87077078, -1.35119677, -1.79559478, -1.77340272],
       [ 1.19335682, -1.14840785, -0.77736403,  0.98152662,  0.95490916],
       [ 1.26339977,  0.87077078, -0.63390585,  1.02064101,  1.38985743],
       [-0.43514185,  0.87077078, -1.13600949, -0.30924811,  0.04547186],
       [-0.22501299,  0.87077078,  2.09179964, -0.11367618,  0.16409412],
       [-1.66089353, -1.14840785,  1.80488328, -1.67825162, -1.89202498],
       [-0.36509889, -1.14840785,  2.02007055, -0.30924811, -0.38947641],
       [ 0.98322796,  0.87077078, -0.63390585,  0.62949715,  0.87582765],
       [ 0.07266956, -1.14840785,  1.08759236,  0.04278136, -0.19177265],
       [ 0.61550245, -1.14840785, -1.42292586,  0.4730396 , -1.61523972],
       [-1.04801769,  0.87077078, -0.56217676, -0.8959639 ,  0.40133863],
       [ 1.0007387 ,  0.87077078,  1.23105054,  0.66861153, -0.62672092],
       [-1.17059286,  0.87077078,  0.22684325, -1.09153583, -1.33845445],
       [ 0.68554541,  0.87077078, -0.77736403,  0.55126838, -0.42901716],
       [ 0.42288433, -1.14840785,  0.08338507,  0.35569645,  1.7457242 ],
       [-0.29505594,  0.87077078,  1.15932145, -0.19190496,  0.28271638],
       [-1.1881036 ,  0.87077078, -1.27946768, -1.13065022,  1.19215367],
       [ 1.1408246 ,  0.87077078, -0.2035313 ,  0.98152662, -0.94304693],
       [-1.22312507, -1.14840785, -1.49465495, -1.13065022,  1.62710194],
       [-1.01299621,  0.87077078, -1.0642804 , -0.8959639 ,  0.55950164],
       [-1.80097944, -1.14840785, -1.42292586, -1.83470916, -0.46855791],
       [-1.06552843, -1.14840785,  0.6572178 , -0.8959639 , -0.58718017],
       [-1.67840427,  0.87077078, -1.13600949, -1.71736601,  1.70618345],
       [-0.38260963, -1.14840785, -0.06007311, -0.30924811,  0.16409412],
       [ 0.87816353,  0.87077078, -0.06007311,  0.62949715,  0.99444991],
       [ 0.913185  ,  0.87077078, -0.84909313,  0.62949715,  1.50847969],
       [-0.26003446,  0.87077078, -0.34698948, -0.15279057,  0.36179788],
       [-0.10243782,  0.87077078, -0.84909313, -0.0745618 , -0.03360964],
       [-0.57522775, -1.14840785,  2.23525783, -0.50482004,  0.16409412],
       [ 1.5961038 ,  0.87077078,  0.58548871,  2.27230136, -1.3779952 ],
       [ 1.40348568,  0.87077078, -0.70563494,  1.41178487,  1.46893893],
       [ 1.03576017, -1.14840785, -1.42292586,  0.74684031, -1.81294348],
       [-1.29316803,  0.87077078, -1.13600949, -1.28710776,  1.42939818],
       [ 1.47352863, -1.14840785, -0.77736403,  1.52912802,  0.6781239 ],
       [-1.62587205, -1.14840785,  2.02007055, -1.67825162, -1.45707671],
       [ 1.33344272, -1.14840785, -0.27526039,  1.21621294,  1.54802044],
       [ 0.33533064,  0.87077078,  0.08338507,  0.27746767,  0.28271638],
       [ 0.14271252,  0.87077078, -1.42292586,  0.04278136,  0.12455337],
       [ 0.03764809,  0.87077078, -1.27946768,  0.00366697, -0.34993565],
       [-0.960464  ,  0.87077078, -0.70563494, -0.85684952, -0.34993565],
       [ 1.57859306,  0.87077078, -0.06007311,  1.99850065,  1.58756119],
       [ 1.3684642 ,  0.87077078, -0.49044767,  1.37267048,  1.38985743],
       [ 0.86065279,  0.87077078,  0.37030144,  0.62949715, -1.2198322 ],
       [-0.64527071,  0.87077078,  0.29857235, -0.54393443, -0.03360964],
       [-1.08303917, -1.14840785, -1.0642804 , -0.93507829,  1.62710194],
       [ 1.28091051, -1.14840785,  1.37450872,  1.02064101, -1.41753596],
       [-1.60836132,  0.87077078, -0.27526039, -1.67825162,  1.9038872 ],
       [-0.41763111,  0.87077078,  0.7289469 , -0.30924811, -0.34993565],
       [-0.47016332,  0.87077078,  0.44203053, -0.30924811,  0.08501262],
       [-0.15497003,  0.87077078, -0.49044767, -0.0745618 , -0.34993565],
       [ 1.22837829, -1.14840785, -0.2035313 ,  0.98152662,  1.62710194],
       [ 0.47541655, -1.14840785,  0.58548871,  0.35569645, -1.65478047],
       [-0.34758816,  0.87077078,  0.51375962, -0.30924811, -0.27085415],
       [-0.31256668, -1.14840785,  0.6572178 , -0.30924811, -0.19177265],
       [-0.80286735, -1.14840785,  2.16352874, -0.70039197, -0.19177265],
       [-1.52080762,  0.87077078, -0.27526039, -1.60002285, -0.62672092],
       [-0.11994856,  0.87077078,  0.58548871, -0.0745618 , -0.15223189],
       [ 0.26528769,  0.87077078,  0.87240508,  0.1992389 , -0.3103949 ],
       [-0.2775452 ,  0.87077078, -1.20773859, -0.19190496,  0.16409412],
       [ 0.79060984,  0.87077078, -0.34698948,  0.62949715, -1.14075069],
       [-0.01488413, -1.14840785,  2.02007055,  0.00366697,  0.32225713],
       [ 1.31593199, -1.14840785,  1.44623782,  1.21621294, -1.45707671],
       [-0.68029218, -1.14840785,  1.73315418, -0.54393443,  0.00593111],
       [ 1.45601789,  0.87077078,  1.08759236,  1.52912802, -1.06166919],
       [-1.5558291 , -1.14840785, -0.13180221, -1.63913723, -1.49661746],
       [ 0.16022326,  0.87077078, -0.06007311,  0.08189575, -0.34993565],
       [ 1.21086756, -1.14840785, -0.2035313 ,  0.98152662, -1.61523972],
       [ 0.80812057, -1.14840785, -0.34698948,  0.62949715,  1.54802044],
       [-0.92544252,  0.87077078,  0.7289469 , -0.77862074,  0.04547186],
       [ 0.12520178, -1.14840785,  1.87661237,  0.04278136,  0.04547186],
       [-0.7328244 , -1.14840785, -1.42292586, -0.6221632 ,  0.16409412],
       [-0.08492708, -1.14840785,  0.6572178 , -0.03544741, -0.34993565],
       [-0.99548547,  0.87077078,  0.80067599, -0.85684952,  0.16409412],
       [ 0.70305614,  0.87077078, -0.49044767,  0.55126838,  1.42939818],
       [ 0.19524473,  0.87077078, -1.49465495,  0.12101013, -0.11269114],
       [ 0.21275547,  0.87077078, -1.42292586,  0.12101013, -0.03360964],
       [ 0.0901803 , -1.14840785,  2.09179964,  0.04278136, -0.3103949 ],
       [-1.20561433,  0.87077078,  0.7289469 , -1.13065022, -1.45707671],
       [-1.7834687 , -1.14840785, -1.27946768, -1.83470916,  1.19215367],
       [-0.54020628,  0.87077078,  1.51796691, -0.46570566, -0.07315039],
       [ 0.94820648,  0.87077078, -0.63390585,  0.62949715,  1.07353141],
       [ 1.07078165, -1.14840785,  0.80067599,  0.90329785, -0.98258769],
       [ 0.7730991 ,  0.87077078, -0.49044767,  0.59038276,  0.91536841],
       [-1.38072172,  0.87077078,  1.08759236, -1.32622215, -1.45707671],
       [-1.71342575,  0.87077078, -1.20773859, -1.75648039,  0.99444991],
       [ 0.51043802,  0.87077078, -0.99255131,  0.39481083, -0.66626167],
       [ 0.72056688, -1.14840785, -0.99255131,  0.59038276, -1.53615821],
       [-0.5051848 , -1.14840785,  1.44623782, -0.30924811, -0.15223189],
       [ 1.42099642,  0.87077078,  0.15511416,  1.45089925, -0.46855791],
       [-0.89042104,  0.87077078, -0.56217676, -0.73950636,  0.12455337],
       [-0.06741634, -1.14840785, -1.35119677, -0.03544741, -0.07315039],
       [-1.73093648,  0.87077078, -0.56217676, -1.75648039, -0.42901716],
       [ 1.49103937,  0.87077078,  0.15511416,  1.6073568 , -1.33845445],
       [ 1.54357158,  0.87077078, -0.49044767,  1.6073568 ,  0.71766465],
       [-0.69780292,  0.87077078,  1.08759236, -0.58304881,  0.32225713],
       [ 1.43850715, -1.14840785, -0.63390585,  1.45089925,  1.8248057 ],
       [-0.78535661,  0.87077078, -0.84909313, -0.6221632 ,  0.00593111],
       [ 0.66803467, -1.14840785, -0.49044767,  0.51215399,  1.66664269],
       [ 0.02013735, -1.14840785,  0.7289469 ,  0.00366697,  0.20363487],
       [-0.94295326,  0.87077078, -0.56217676, -0.85684952, -0.34993565],
       [ 1.61361454,  0.87077078, -0.27526039,  2.27230136,  1.11307217],
       [ 0.59799171, -1.14840785, -0.49044767,  0.43392522,  0.87582765],
       [ 0.28279842,  0.87077078,  0.80067599,  0.1992389 ,  0.24317562],
       [-1.46827541,  0.87077078, -0.27526039, -1.52179408,  1.86434645],
       [ 1.08829239,  0.87077078, -0.2035313 ,  0.90329785,  0.95490916],
       [ 0.63301319,  0.87077078, -0.27526039,  0.4730396 ,  0.8362869 ],
       [ 0.45790581, -1.14840785, -0.06007311,  0.35569645,  0.95490916],
       [-1.48578615, -1.14840785,  0.94413417, -1.52179408, -0.86396543],
       [-1.59085058,  0.87077078,  1.37450872, -1.63913723, -1.41753596],
       [ 0.30030916, -1.14840785, -0.84909313,  0.1992389 ,  0.20363487],
       [ 0.37035212,  0.87077078, -1.13600949,  0.31658206, -0.86396543],
       [-0.71531366,  0.87077078,  2.02007055, -0.58304881,  0.04547186],
       [ 0.44039507, -1.14840785,  1.44623782,  0.35569645, -1.57569896],
       [ 1.01824943,  0.87077078, -0.70563494,  0.66861153,  1.27123517],
       [-0.20750225, -1.14840785, -1.49465495, -0.11367618, -0.38947641],
       [ 0.24777695,  0.87077078,  0.7289469 ,  0.12101013,  0.32225713],
       [-1.1005499 ,  0.87077078,  1.87661237, -0.93507829, -0.62672092],
       [-0.76784588, -1.14840785,  1.01586326, -0.6221632 , -0.19177265],
       [ 1.35095346,  0.87077078, -0.13180221,  1.37267048, -0.74534317],
       [-1.41574319,  0.87077078,  0.51375962, -1.4435653 , -1.81294348],
       [-0.66278145, -1.14840785, -1.49465495, -0.54393443,  0.32225713],
       [ 0.38786285,  0.87077078, -0.56217676,  0.31658206,  1.03399066],
       [ 0.82563131, -1.14840785,  0.29857235,  0.62949715, -1.33845445],
       [-0.82037809,  0.87077078,  0.87240508, -0.70039197, -0.03360964],
       [ 1.38597494, -1.14840785,  0.51375962,  1.41178487, -1.41753596],
       [ 1.68365749, -1.14840785, -0.63390585,  2.93724592,  1.27123517],
       [-0.18999151, -1.14840785,  0.6572178 , -0.0745618 , -0.07315039],
       [ 0.40537359, -1.14840785,  0.29857235,  0.35569645, -0.62672092]])

In [18]:
pipeline=Pipeline([
        ("scaler", StandardScaler()),
         ("model", KMeans(n_clusters=2,random_state=9))

])

In [19]:
pipeline.fit(X_train)

Pipeline(steps=[('scaler', StandardScaler()),
                ('model', KMeans(n_clusters=2, random_state=9))])

# Custom scorer for clustering

In [20]:
def silhouette_scorer(KMeans, X):
    labels = KMeans.fit_predict(X)
    return silhouette_score(X, labels)

#GridSearchCV

In [21]:
params ={
    "model__n_clusters" : [ 2,4,6,8],
    "model__copy_x": [True,False],
    "model__algorithm" : ["lloyd","elkan"]


}


grid =GridSearchCV(estimator=pipeline, cv=3 ,param_grid=params,scoring=silhouette_scorer)

# fit grid on training data

In [22]:
grid.fit(X_train)

GridSearchCV(cv=3,
             estimator=Pipeline(steps=[('scaler', StandardScaler()),
                                       ('model',
                                        KMeans(n_clusters=2, random_state=9))]),
             param_grid={'model__algorithm': ['lloyd', 'elkan'],
                         'model__copy_x': [True, False],
                         'model__n_clusters': [2, 4, 6, 8]},
             scoring=<function silhouette_scorer at 0x000001FEFA124510>)

In [23]:
print(grid.best_params_)

{'model__algorithm': 'lloyd', 'model__copy_x': True, 'model__n_clusters': 2}

# Evaluating our model by comparing with others clusters

In [24]:
for k in range(2, 9):
    km = KMeans(n_clusters=k, random_state=42)
    labels = km.fit_predict(X)
    print(k, silhouette_score(X, labels))

2 0.4793049017423563
3 0.3766801400675223
4 0.42245261332521894
5 0.4336704604654853
6 0.4136658769610973
7 0.36023293127992717
8 0.4039697220630983

 TWO CLUSTERS : These customers have money but they don't spend much .These categories of people are referred to as conservaties buyers ,they are the middle-aged to older and Whose income are high are high and are low spenders.
 FOUR CLUSTERS: These are  low income and high spenders (young cusomers).They spend beyond their income levels .They are buyers at puchase at the slighest opportunity following what is trending in the market.These sets  of people are sensitive to promotions and credit offers.
 SIX CLUSTERS :There is medium income earners, medium  spenders .These set of people are reffered to as moderate spenders .They are good for general marketing campaigns.