In [130]:
import  pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import silhouette_score

# Import dataset into jupyter notebook

In [131]:
df= pd.read_csv("Mall_Customers.csv") 
df.head()

   CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0           1    Male   19                  15                      39
1           2    Male   21                  15                      81
2           3  Female   20                  16                       6
3           4  Female   23                  16                      77
4           5  Female   31                  17                      40

In [132]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 5 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   CustomerID              200 non-null    int64
 1   Gender                  200 non-null    str
 2   Age                     200 non-null    int64
 3   Annual Income (k$)      200 non-null    int64
 4   Spending Score (1-100)  200 non-null    int64
dtypes: int64(4), str(1)
memory usage: 7.9 KB

In [133]:
df.describe()

       CustomerID         Age  Annual Income (k$)  Spending Score (1-100)
count  200.000000  200.000000          200.000000              200.000000
mean   100.500000   38.850000           60.560000               50.200000
std     57.879185   13.969007           26.264721               25.823522
min      1.000000   18.000000           15.000000                1.000000
25%     50.750000   28.750000           41.500000               34.750000
50%    100.500000   36.000000           61.500000               50.000000
75%    150.250000   49.000000           78.000000               73.000000
max    200.000000   70.000000          137.000000               99.000000

# Check for missing numbers

In [134]:
df.isnull().sum()

CustomerID                0
Gender                    0
Age                       0
Annual Income (k$)        0
Spending Score (1-100)    0
dtype: int64

Encode dataset

In [135]:
df["Gender"].unique()

<StringArray>
['Male', 'Female']
Length: 2, dtype: str

In [136]:
cat_col = df["Gender"]   
print (cat_col)

0        Male
1        Male
2      Female
3      Female
4      Female
        ...
195    Female
196    Female
197      Male
198      Male
199      Male
Name: Gender, Length: 200, dtype: str

# Encoding by mapping

In [137]:
df["Gender"]=df["Gender"].map({"Male":0,"Female":1})

In [138]:
df.head()

   CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0           1       0   19                  15                      39
1           2       0   21                  15                      81
2           3       1   20                  16                       6
3           4       1   23                  16                      77
4           5       1   31                  17                      40

In [139]:
X = np.array([
    [0, 19, 15, 39],
    [0, 21, 15, 81],
    [1, 20, 16,  6],
    [1, 23, 16, 77],
   [1, 31, 17,  40]

])

Divide features into training and testing set

In [140]:
X_train,X_test=train_test_split(X,train_size=0.8,random_state=9)

# import scaler

In [141]:
scaler =StandardScaler()  
scaler.fit_transform(X_train)

array([[-1.        , -0.7787612 , -0.90453403, -0.09400556],
       [-1.        , -0.36342189, -0.90453403,  1.48528781],
       [ 1.        , -0.57109154,  0.30151134, -1.33487892],
       [ 1.        ,  1.71327463,  1.50755672, -0.05640333]])

In [144]:
pipeline=Pipeline([
        ("scaler", StandardScaler()),
         ("model", KMeans(n_clusters=2,random_state=9))

])

In [145]:
pipeline.fit(X_train)

Pipeline(steps=[('scaler', StandardScaler()),
                ('model', KMeans(n_clusters=2, random_state=9))])

# Custom scorer for clustering

In [148]:
def silhouette_scorer(estimator, X):
    labels = estimator.fit_predict(X)
    return silhouette_score(X, labels)

GridSearchCV

In [149]:
params ={
    "Model__n_clusters" : [ 2,4,6,8],
    "Model__copy_x": [True,False],
    "Model__algorithm" : ["lloyd","elkan"]


}


grid = GridSearchCV(estimator=pipeline, cv=3 ,param_grid=params,scoring=silhouette_scorer)

# fit grid on training data

In [151]:
grid.fit(X_train)

ValueError: Invalid parameter 'Model' for estimator Pipeline(steps=[('scaler', StandardScaler()),
                ('model', KMeans(n_clusters=2, random_state=9))]). Valid parameters are: ['memory', 'steps', 'transform_input', 'verbose'].